---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  get-version:
    uses: GrabAByte/github-devops-workflows/.github/workflows/getVersion.yml@0.0.5
    with:
      metadataFile: 'metadata.json'
      metadataPath: .
  groovy-lint:
    uses: GrabAByte/github-devops-workflows/.github/workflows/groovyLint.yml@feat/groovyci
    with:
      groovyPath: .
    needs: get-version
  update-version:
    uses: GrabAByte/github-devops-workflows/.github/workflows/updateVersion.yml@0.0.5
    with:
      gitUsername: 'grababyte'
      gitEmail: 'grababyte@github.com'
      metadataFile: 'metadata.json'
      metadataPath: .
    needs: groovy-lint

