---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  groovy-ci:
    steps:
      - uses: GrabAByte/github-devops-workflows/.github/workflows/groovyLint.yml@feat/groovyci
      - uses: GrabAByte/github-devops-workflows/.github/workflows/yamlLint.yml@feat/groovyci
